global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nanomq'
    metrics_path: '/api/v4/prometheus'
    scheme: http
    basic_auth:
      username: admin
      password: public
    static_configs:
      - targets: ['nanomq:8081']
